# Generated by Django 4.2 on 2023-04-18 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_n_lives'),
    ]

    operations = [
        migrations.CreateModel(
            name='Q_choose_option_answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_text', models.CharField(max_length=4000)),
                ('correct_answer', models.BooleanField()),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q_choose_option_answers', to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='Q_choose_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_text', models.CharField(max_length=4000)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qs_choose_option', to='tasks.task')),
            ],
        ),
    ]
