# Generated by Django 4.2 on 2023-04-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_q_choose_option_answers_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q_choose_option_answers',
            name='correct_answer',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
