# Generated by Django 4.2 on 2023-04-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_q_choose_option_answers_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='q_choose_option',
            name='options_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='q_choose_option_answers',
            name='option_n',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
