# Generated by Django 4.2 on 2023-04-18 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_rename_task_q_choose_option_answers_q_choose_option_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Q_choose_option_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_text', models.CharField(max_length=4000)),
                ('option_n', models.PositiveIntegerField(default=0)),
                ('correct_answer', models.BooleanField()),
                ('q_choose_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q_choose_option_answers', to='tasks.q_choose_option')),
            ],
        ),
        migrations.DeleteModel(
            name='Q_choose_option_answers',
        ),
    ]
